### PR TITLE
Add Valora

### PR DESCRIPTION
**Pull request by mnebes**
We are using F# for our backend services at Valora Digital. We posted some job offers in F# Slack and were on one of Don's slides on "F# Community Bonanza" :)

### CODE REVIEW

**Review by jayhill — APPROVED** [review]

**Comment by dsyme** [comment]
Please also consider submitting a testimonial to https://fsharp.org/testimonials! :))

**Comment by dsyme** [comment]
We should put this in the README for this repo if it's not there already

**Comment by jayhill** [comment]
@dsyme What should be in the README?
Valora was added via this PR; I want to make sure I'm not missing something else.

**Comment by dsyme** [comment]
@jayhill We should mention that people should also consider submitting a testimonial to https://fsharp.org/testimonials, thanks

**Pull request merged**
